### ISSUE TITLE
你好，请问这些节点要怎么使用呢

### ISSUE THREAD

**Issue by yufeiyang2008** [bingoYB/node_processing#2]
你好，请问这些节点要怎么使用呢，all.yaml要怎么导入到代理软件里呢

**Comment by bingoYB** [comment]
github有源文件内容的地址的
![image](https://user-images.githubusercontent.com/24823972/220358525-50200cd3-2845-42a6-b601-1ed4684bc9be.png)

**Comment by bingoYB** [comment]
github有源文件内容的地址的
![image](https://user-images.githubusercontent.com/24823972/220358623-e0617a44-ea2d-4d43-93b7-8ba7a2bd0143.png)

**Comment by yufeiyang2008** [comment]
> github有源文件内容的地址的 ![图像](https://user-images.githubusercontent.com/24823972/220358623-e0617a44-ea2d-4d43-93b7-8ba7a2bd0143.png)

这个链接不能直接当订阅链接用啊！是不是得特定的软件
